### ISSUE TITLE
Can't install xmm-lfo with "npm install [--save] Ircam-RnD/xmm-lfo"

### ISSUE THREAD

**Issue by frantic0** [Ircam-RnD/xmm-lfo#1]

**Comment by josephlarralde** [comment]
It's working on my computer (osx 10.11.6, node v4.4.4, npm v3.10.5)

Could you provide more details ? Your configuration and which error messages you get in the terminal, if any ?

If you try the following : 
- create a folder somewhere
- from this folder, type npm init and hit enter until the package.json file is created
- type npm install --save Ircam-RnD/xmm-lfo

Is it still not working ?
At this point you should see xmm-lfo in the automatically created node_modules folder

**Comment by frantic0** [comment]
Hi Joseph,

here's my setup: OS X 10.11.6, node v6.7.0, npm 3.10.3

sorry I didn't post the initial log, it's quite long, here a bit of its tail..

`
12 warnings and 14 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error:`make`failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/francisco/Documents/Development/RAPID-MIX/node_modules/utf-8-validate
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install:`node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
npm WARN saveError ENOENT: no such file or directory, open '/Users/francisco/Documents/Development/RAPID-MIX/package.json'
/Users/francisco/Documents/Development/RAPID-MIX
└─┬ xmm-lfo@0.2.0  (git://github.com/ircam-rnd/xmm-lfo.git#69ef6467ea7a1b81672c9fe43ccd28503807c14f)
  ├─┬ waves-lfo@0.2.0  (git://github.com/wavesjs/waves-lfo.git#01f7578661384ebfd85249fd4f792d0dbf458bf7)
  │ └── jsfft@0.0.1  (git://github.com/dntj/jsfft.git#b82257673c97f5f4bfc12fe445dcf1cf2169b46e)
  └── xmm-client@0.1.0  (git://github.com/ircam-rnd/xmm-client.git#9d3c22d1c4ffbf5c92e018274be5412a4c64bdfc)

npm WARN enoent ENOENT: no such file or directory, open '/Users/francisco/Documents/Development/RAPID-MIX/package.json'
npm WARN RAPID-MIX No description
npm WARN RAPID-MIX No repository field.
npm WARN RAPID-MIX No README data
npm WARN RAPID-MIX No license field.
`

also tried to do what you've said. And no go, here's the log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "install" "--save" "Ircam-RnD/xmm-lfo"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code ENOSELF

npm ERR! Refusing to install xmm-lfo as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/francisco/Documents/Development/RAPID-MIX/xmm-lfo/npm-debug.log

Is there any dependency from the other packages?

Thanks

**Comment by NorbertSchnell** [comment]
I guess, we are not ready for node.js 6.
Can you try this : 
  https://nodejs.org/en/blog/release/v4.6.1/
N.

**Comment by josephlarralde** [comment]
Hmmm, doesn't seem to be a version issue.
At least I was able to install it on my machine with several node 6 versions, including node 6.7.0 with npm 3.10.3, with the usual error messages from utf-8-validate of course, but which don't prevent the module from installing.

I'm working on the port to the new lfo api these days, I'll let you know.

More luck with v4 ?

**Comment by josephlarralde** [comment]
Hey Francisco, any update on this ? May I close the issue ?
